spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes[0]:
        id: user-service-route
        uri: http://localhost:7001
        predicates:
          - Path=/user-service/v1/users
        filters:
          - RewritePath=/user-service/v1/users, /v1/users
      routes[1]:
        id: invoice-service-route
        uri: http://localhost:7002
        predicates:
          - Path=/invoice-service/v1/invoices
        filters:
          - RewritePath=/invoice-service/v1/invoices, /v1/invoices

server:
  port: 6500