global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'invoice-service-job'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:7002' ]
  - job_name: 'user-service-job'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:7001' ]
#  - job_name: 'product-service-job'
#    metrics_path: '/actuator/prometheus'
#    static_configs:
#      - targets: [ 'product-service:7003' ]
