spring:
  application:
    name: invoice-service

  flyway:
    default-schema: invoice_db
  locations:
    - classpath:db/migrations

server:
  port: 7002

logstash:
  host: localhost
  port: 50000

management:
  tracing:
    propagation:
      consume: W3C